import { getEnv } from "../utils/get-env";

const envConfig = () => ({
  NODE_ENV: getEnv("NODE_ENV", "development"),

  PORT: getEnv("PORT", "8000"),
  BASE_PATH: getEnv("BASE_PATH", "/api"),
  // Azure SQL Database Configuration
  AZURE_SQL_SERVER: getEnv("AZURE_SQL_SERVER"),
  AZURE_SQL_DATABASE: getEnv("AZURE_SQL_DATABASE"),
  AZURE_SQL_USER: getEnv("AZURE_SQL_USER"),
  AZURE_SQL_PASSWORD: getEnv("AZURE_SQL_PASSWORD"),

  // Azure Blob Storage Configuration
  AZURE_STORAGE_ACCOUNT: getEnv("AZURE_STORAGE_ACCOUNT"),
  AZURE_STORAGE_KEY: getEnv("AZURE_STORAGE_KEY"),
  AZURE_STORAGE_CONNECTION_STRING: getEnv("AZURE_STORAGE_CONNECTION_STRING", ""),
  AZURE_STORAGE_SAS_URL: getEnv("AZURE_STORAGE_SAS_URL", ""),


  GEMINI_API_KEY: getEnv("GEMINI_API_KEY"),

  CLOUDINARY_CLOUD_NAME: getEnv("CLOUDINARY_CLOUD_NAME"),
  CLOUDINARY_API_KEY: getEnv("CLOUDINARY_API_KEY"),
  CLOUDINARY_API_SECRET: getEnv("CLOUDINARY_API_SECRET"),

  RESEND_API_KEY: getEnv("RESEND_API_KEY"),
  RESEND_MAILER_SENDER: getEnv("RESEND_MAILER_SENDER", ""),

  FRONTEND_ORIGIN: getEnv("FRONTEND_ORIGIN", "http://localhost:5173"),
});

export const Env = envConfig();
